#vi:ft=ruby:
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'universal-ctags/universal-ctags'

brew 'tmux'
brew 'neovim', args: %w[HEAD]
brew 'ag'
brew 'universal-ctags', args: %w[HEAD]
brew 'bash-completion'
brew 'openssl'
brew 'node'
brew 'redis'
brew 'wget'
brew 'go'
brew 'git'
brew 'hub'
brew 'ffmpeg', args: %w[--with-libvpx --with-libvorbis]

tap 'caskroom/cask'
cask '1password'
cask 'spotify'
cask 'iterm2'
cask 'slack'
cask 'alfred'
cask 'charles'
cask 'skype'
cask 'firefox'
cask 'google-chrome'
cask 'caffeine'
cask 'vlc'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code-insiders'
cask 'daisydisk'
