#vi:ft=ruby:
tap 'homebrew/services'

brew 'bash-completion'
brew 'curl'
brew 'fasd'
brew 'fzf'
brew 'git'
brew 'go'
brew 'hub'
brew 'neovim', args: %w[HEAD]
brew 'nvm'
brew 'openssl'
brew 'rbenv'
brew 'readline'
brew 'ripgrep'
brew 'ruby-build'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'git-crypt'
brew 'git-delta'
brew 'jq'
brew 'yq'
brew 'exa'
brew 'bat'
brew 'bat-extras'
brew 'urlview'
brew 'starship'
brew 'gh'
brew 'spotify-tui'
brew 'spotifyd'

cask '1password'
cask 'rectangle'
cask 'firefox'
cask 'iterm2'
cask 'alacritty'
cask 'spotify'
cask 'visual-studio-code'
cask 'keka'
cask 'font-hack-nerd-font'
cask 'amethyst'
