bindkey -e
export KEYTIMEOUT=1
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export CLICOLOR=1

if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

HISTSIZE=5000
SAVEHIST=5000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

eval "$(fasd --init auto )"
eval "$(rbenv init -)"

#GIT
alias gs='git status'
alias gcm='git commit -m'
alias ga='git add'
alias gl='git log'
alias gco='git checkout'
alias gconflicts='git diff --name-only --diff-filter=U'

alias pull='git pull --rebase'
alias push='git push'

#SYSTEM
alias python=python3
alias pip=pip3
alias vim=nvim
alias _=sudo
alias gz='tar -zcvf' #tar a folder
alias ll='exa -lah'

alias zl='source ~/.zshrc'
alias ze='vim ~/.zshrc'

#RAILS
alias c='clear'
alias :q='exit'
alias rmf='rm -rf'
alias tailf='tail -f'

#FASD
unalias z
unalias zz

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias j='fasd_cd -d'     # cd, same functionality as j in autojump
alias jj='fasd_cd -d -i' # cd with interactive selection

#OFFICE
alias jira='git fetch && git checkout --track $(git branch -r | fzf)'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

alias ls=exa
alias cat=bat
alias man=batman

export EDITOR=nvim
export PATH=$HOME/dotfiles/bin:$PATH

fpath=(~/.zsh/completion $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)
. $(brew --prefix)/share/zsh/site-functions

#IMPORT FILES
source $HOME/dotfiles/zsh/functions
[ -f $HOME/.zsh_profile ] && source $HOME/.zsh_profile

export HOMEBREW_NO_ANALYTICS=1

export PATH="/usr/local/opt/ruby/bin:$PATH"

### JAVA SHIT
export PATH="/usr/local/sbin:$PATH"
export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export JAVA_11_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home

#Java
alias java8='export JAVA_HOME=$JAVA_8_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'
java8

eval "$(starship init zsh)"
eval "$(goenv init -)"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

# FZF setup
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type file --hidden --no-ignore'
export FZF_COMPLETION_TRIGGER='~~'

# Node version manager
source nvm_settings.sh


# Android Setup
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Python3 setup
export PATH="$HOME/.poetry/bin:$PATH"

# Rust
source $HOME/.cargo/env
export PATH="$HOME/.cargo/bin:$PATH"

source ~/.alacritty.sh
